"""Stored file name

Revision ID: c27fec0d7936
Revises: fa99d7e2ae40
Create Date: 2021-03-02 14:56:40.975656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27fec0d7936'
down_revision = 'fa99d7e2ae40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_file', sa.Column('stored_file_name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_published_file_stored_file_name'), 'published_file', ['stored_file_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_published_file_stored_file_name'), table_name='published_file')
    op.drop_column('published_file', 'stored_file_name')
    # ### end Alembic commands ###
