"""Add token

Revision ID: cbfdc346f80b
Revises: 10ee1ed816e7
Create Date: 2021-03-16 10:07:45.866305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbfdc346f80b'
down_revision = '10ee1ed816e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_token_expire_at'), 'token', ['expire_at'], unique=False)
    op.create_index(op.f('ix_token_username'), 'token', ['username'], unique=False)
    op.create_unique_constraint(None, 'published_file', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'published_file', type_='unique')
    op.drop_index(op.f('ix_token_username'), table_name='token')
    op.drop_index(op.f('ix_token_expire_at'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
