"""Version

Revision ID: fa99d7e2ae40
Revises: 925a2c465d4f
Create Date: 2021-02-25 16:46:07.689347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa99d7e2ae40'
down_revision = '925a2c465d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_file', sa.Column('version', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_published_file_version'), 'published_file', ['version'], unique=False)
    op.create_unique_constraint(None, 'published_file', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'published_file', type_='unique')
    op.drop_index(op.f('ix_published_file_version'), table_name='published_file')
    op.drop_column('published_file', 'version')
    # ### end Alembic commands ###
